import {
  Home,
  Info,
  GraduationCap,
  Building2,
  ClipboardList,
  Phone,
} from "lucide-react";

import type { PageKey, PageTab, SectionItem } from "./adminTypes";

export const pageTabs: PageTab[] = [
  {
    id: "home",
    label: "Home",
    icon: Home,
  },
  {
    id: "about",
    label: "About",
    icon: Info,
  },
  {
    id: "academics",
    label: "Academics",
    icon: GraduationCap,
  },
  {
    id: "facilities",
    label: "Facilities",
    icon: Building2,
  },
  {
    id: "admissions",
    label: "Admissions",
    icon: ClipboardList,
  },
  {
    id: "contact",
    label: "Contact",
    icon: Phone,
  },
];

export const pageSections: Record<PageKey, SectionItem[]> = {
  home: [
    {
      id: "homeHero",
      label: "Hero Section",
      description: "Edit the homepage hero banner, heading, buttons, and visual card.",
      fields: [
        "Kicker",
        "Title",
        "Description",
        "Primary Button Text",
        "Primary Button Link",
        "Secondary Button Text",
        "Secondary Button Link",
        "Hero Background / Image Class",
        "Mini Card Value",
        "Mini Card Label",
        "Visual Eyebrow",
        "Visual Title",
        "Visual Description",
      ],
    },
    {
      id: "homeHeroHighlights",
      label: "Hero Highlights",
      description: "Manage the highlight rows inside the homepage hero panel.",
      fields: ["Highlight Text"],
    },
    {
      id: "homeTrustTags",
      label: "Hero Trust Tags",
      description: "Manage small trust tags such as Discipline, Confidence, Creativity, and Care.",
      fields: ["Tag Name"],
    },
    {
      id: "homeQuickFacts",
      label: "Quick Facts",
      description: "Manage the statistic cards below the hero section.",
      fields: ["Value", "Label"],
    },
    {
      id: "homeIntro",
      label: "Intro / About Preview",
      description: "Manage the homepage about preview section.",
      fields: ["Eyebrow", "Title", "Description", "Card Description"],
    },
    {
      id: "homeFeatureCards",
      label: "Intro Feature Cards",
      description: "Manage the three feature cards below the intro section.",
      fields: ["Label", "Title", "Description", "Strong Card true/false"],
    },
    {
      id: "homeCampusPhotos",
      label: "Campus Photo Cards",
      description: "Manage the three campus image cards.",
      fields: ["Title", "Image URL / CSS Class", "Order"],
    },
    {
      id: "homeStrengths",
      label: "Why Choose Us",
      description: "Manage homepage strength cards.",
      fields: ["Label", "Title", "Description"],
    },
    {
      id: "homePrograms",
      label: "Academic Programs Preview",
      description: "Manage program tabs shown on the homepage.",
      fields: ["Stage", "Title", "Description"],
    },
    {
      id: "homeFacilitiesPreview",
      label: "Facilities Preview",
      description: "Manage small facility cards shown on homepage.",
      fields: ["Title", "Description"],
    },
    {
      id: "homeUpdates",
      label: "Latest Updates",
      description: "Manage latest update cards shown in the dark panel.",
      fields: ["Label / Date", "Title", "Description"],
    },
    {
      id: "homeFinalCta",
      label: "Final CTA",
      description: "Manage the final homepage call-to-action.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Primary Button Text",
        "Primary Button Link",
        "Secondary Button Text",
        "Secondary Button Link",
      ],
    },
  ],

  about: [
    {
      id: "aboutHero",
      label: "Hero Section",
      description: "Edit the main About page heading, intro text, and buttons.",
      fields: [
        "Kicker",
        "Title",
        "Description",
        "Primary Button Text",
        "Primary Button Link",
        "Secondary Button Text",
        "Secondary Button Link",
      ],
    },
    {
      id: "aboutHeroCarousel",
      label: "Hero Carousel",
      description: "Manage the image slider shown on the right side of the About hero.",
      fields: ["Image URL", "Label", "Title", "Description"],
    },
    {
      id: "aboutQuickFacts",
      label: "Quick Facts",
      description: "Manage the small fact cards shown below the hero text.",
      fields: ["Value", "Label"],
    },
    {
      id: "aboutColorStrip",
      label: "Color Strip Cards",
      description: "Manage the four small feature cards below the hero.",
      fields: ["Icon Name", "Title", "Color Class"],
    },
    {
      id: "aboutIdentityTabs",
      label: "Identity Tabs",
      description: "Manage Mission, Vision, and Promise tab content.",
      fields: [
        "Key",
        "Label",
        "Icon Name",
        "Gradient Class",
        "Title",
        "Description",
      ],
    },
    {
      id: "aboutFeeCalculator",
      label: "Fee Calculator",
      description: "Manage demo fee calculator values.",
      fields: [
        "Pre-Primary Base Fee",
        "Primary Base Fee",
        "Secondary Base Fee",
        "Transport Fee",
        "Hostel Fee",
        "Note Text",
      ],
    },
    {
      id: "aboutFitChecker",
      label: "School Fit Checker",
      description: "Manage fit checker questions and result messages.",
      fields: ["Question", "Result Message"],
    },
    {
      id: "aboutCoreValues",
      label: "Core Values",
      description: "Manage the three core value cards.",
      fields: ["Title", "Description", "Icon Name", "Color Class"],
    },
    {
      id: "aboutAlbum",
      label: "School Album",
      description: "Manage filterable album images.",
      fields: ["Image URL", "Title", "Category", "Alt Text"],
    },
    {
      id: "aboutFaq",
      label: "FAQ Section",
      description: "Manage About page accordion questions and answers.",
      fields: ["Question", "Answer"],
    },
    {
      id: "aboutCta",
      label: "CTA Section",
      description: "Manage the final campus visit call-to-action.",
      fields: ["Eyebrow", "Title", "Description", "Button Text", "Button Link"],
    },
  ],

  academics: [
    {
      id: "academicsHero",
      label: "Hero Section",
      description: "Manage the top hero content, intro text, and hero buttons.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Primary Button Text",
        "Primary Button Link",
        "Secondary Button Text",
        "Secondary Button Link",
      ],
    },
    {
      id: "academicsHeroPanel",
      label: "Hero Academic Focus Panel",
      description: "Manage the right-side hero panel content.",
      fields: [
        "Icon Name",
        "Eyebrow",
        "Title",
        "Description",
        "Gradient Class",
      ],
    },
    {
      id: "academicsHeroStats",
      label: "Hero Focus Stats",
      description: "Manage the three small cards below the academic focus panel.",
      fields: ["Number", "Label"],
    },
    {
      id: "academicsProgramIntro",
      label: "Program Levels Intro",
      description: "Manage the heading and description above the program level tabs.",
      fields: ["Eyebrow", "Title", "Description"],
    },
    {
      id: "academicsPrograms",
      label: "Program Level Tabs",
      description: "Manage the interactive academic program level buttons.",
      fields: ["Title", "Description", "Icon Name", "Active true/false"],
    },
    {
      id: "academicsSelectedLevel",
      label: "Selected Level Card",
      description: "Manage the selected program level detail card.",
      fields: ["Eyebrow", "Title", "Description"],
    },
    {
      id: "academicsLearningCycleIntro",
      label: "Learning Cycle Intro",
      description: "Manage the heading and description for the learning cycle section.",
      fields: ["Eyebrow", "Title", "Description"],
    },
    {
      id: "academicsLearningFlow",
      label: "Learning Cycle Cards",
      description: "Manage the step-by-step learning cycle cards.",
      fields: ["Step Number", "Title", "Description", "Color Class"],
    },
    {
      id: "academicsLearningPath",
      label: "Learning Path Panel",
      description: "Manage the dark interactive learning path panel.",
      fields: ["Icon Name", "Eyebrow", "Title", "Description"],
    },
    {
      id: "academicsLearningStyles",
      label: "Learning Style Buttons",
      description: "Manage Concept First, Practice Daily, and Present Clearly tabs.",
      fields: ["Key", "Title", "Description", "Active true/false"],
    },
    {
      id: "academicsSelectedApproach",
      label: "Selected Approach Card",
      description: "Manage the selected learning approach card and classroom outcome text.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Outcome Title",
        "Outcome Description",
      ],
    },
    {
      id: "academicsAreasIntro",
      label: "Academic Areas Intro",
      description: "Manage the heading and description for the academic areas section.",
      fields: ["Eyebrow", "Title", "Description"],
    },
    {
      id: "academicsAreas",
      label: "Academic Area Cards",
      description: "Manage Language, Mathematics, Science, and Creative academic area cards.",
      fields: ["Eyebrow", "Title", "Description", "Icon Name", "Color Class"],
    },
    {
      id: "academicsCta",
      label: "Final CTA Section",
      description: "Manage the bottom admissions call-to-action section.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Button Text",
        "Button Link",
        "Gradient Class",
      ],
    },
  ],

  facilities: [
    {
      id: "facilitiesHero",
      label: "Hero Section",
      description: "Manage the top Facilities page hero section.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
      ],
    },
    {
      id: "facilitiesHeroPanel",
      label: "Hero Campus View Panel",
      description: "Manage the right-side hero panel content.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Button Text",
        "Button Link",
      ],
    },
    {
      id: "facilitiesCampusFeaturesIntro",
      label: "Campus Features Intro",
      description: "Manage the heading and description above the facility cards.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Alignment",
      ],
    },
    {
      id: "facilitiesCards",
      label: "Campus Feature Cards",
      description: "Manage the main facility cards shown under Campus Features.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
      ],
    },
    {
      id: "facilitiesSupportIntro",
      label: "Support Environment Intro",
      description: "Manage the heading and description for the support environment section.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
      ],
    },
    {
      id: "facilitiesSupportAreas",
      label: "Support Environment Cards",
      description: "Manage Safety, Student Expression, and Balanced Development cards.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
      ],
    },
  ],

  admissions: [
    {
      id: "admissionsHero",
      label: "Hero Section",
      description: "Manage the top Admissions page hero section.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Primary Button Text",
        "Primary Button Link",
        "Secondary Button Text",
        "Secondary Button Link",
      ],
    },
    {
      id: "admissionsHeroPanel",
      label: "Parent Journey Panel",
      description: "Manage the right-side hero panel content.",
      fields: [
        "Icon Name",
        "Eyebrow",
        "Title",
        "Description",
      ],
    },
    {
      id: "admissionsHeroChecklist",
      label: "Parent Journey Checklist",
      description: "Manage the checklist items inside the hero panel.",
      fields: [
        "Checklist Text",
      ],
    },
    {
      id: "admissionStepsIntro",
      label: "Admission Steps Intro",
      description: "Manage the heading and description above the admission step cards.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Alignment",
      ],
    },
    {
      id: "admissionSteps",
      label: "Admission Step Cards",
      description: "Manage the step-by-step admission process cards.",
      fields: [
        "Step Number",
        "Title",
        "Description",
        "Icon Name",
      ],
    },
    {
      id: "admissionDocumentsIntro",
      label: "Required Documents Intro",
      description: "Manage the left-side documents section heading and help text.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Info Box Icon Name",
        "Info Box Description",
      ],
    },
    {
      id: "admissionDocuments",
      label: "Required Document List",
      description: "Manage documents needed during admission discussion.",
      fields: [
        "Document Name",
        "Order Number",
      ],
    },
    {
      id: "admissionFaqIntro",
      label: "FAQ Intro",
      description: "Manage the heading and description above the FAQ cards.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Alignment",
      ],
    },
    {
      id: "admissionFaq",
      label: "FAQ Cards",
      description: "Manage frequently asked admission questions and answers.",
      fields: [
        "Eyebrow",
        "Question",
        "Answer",
        "Icon Name",
      ],
    },
    {
      id: "admissionsCta",
      label: "Final CTA Section",
      description: "Manage the bottom admission call-to-action section.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Primary Button Text",
        "Primary Button Link",
        "Secondary Button Text",
        "Secondary Button Link",
      ],
    },
  ],

  contact: [
    {
      id: "contactHero",
      label: "Hero Section",
      description: "Manage the top Contact page hero section.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
      ],
    },
    {
      id: "contactStartPanel",
      label: "Start Here Panel",
      description: "Manage the right-side form selection card in the hero section.",
      fields: [
        "Eyebrow",
        "Title",
        "Primary Button Text",
        "Primary Button Link",
        "Secondary Button Text",
        "Secondary Button Link",
      ],
    },
    {
      id: "contactDetailsIntro",
      label: "Contact Details Intro",
      description: "Manage the heading and description above the contact detail cards.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
      ],
    },
    {
      id: "contactDetails",
      label: "Contact Detail Cards",
      description: "Manage phone, email, address, opening hours, and other school contact information.",
      fields: [
        "Label",
        "Value",
      ],
    },
    {
      id: "contactVisitIntro",
      label: "Why Visit Intro",
      description: "Manage the heading and description for the campus visit section.",
      fields: [
        "Eyebrow",
        "Title",
        "Description",
        "Alignment",
      ],
    },
    {
      id: "contactVisitReasons",
      label: "Why Visit Cards",
      description: "Manage Campus Introduction, Academic Conversation, and Admission Guidance cards.",
      fields: [ 
        "Eyebrow",
        "Title",
        "Description",
      ],
    },
  ],
};